name: Node CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest
    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v6
        # Step's name
      - name: Use Node.js 24
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v6
        # The Node.js version to configure
        with:
          node-version: 24
          cache: 'npm'
      - run: make ci
      - run: make lint
  